ScopeGraph: introduce ScopeGraph
revng/revng-c pull request #43
Opened 2024-10-30 17:02 UTC by andrealinux1

Introduce the `ScopeGraph` view over an `llvm::Function`, and the necessary utilities to have `Dashed` and `Goto` edges over it.

2024-11-20 22:39 UTC, pfez requested changes

2024-11-20 22:39 UTC, pfez commented on include/revng-c/RestructureCFG/GeneratorIterator.h
> +  using difference_type = unsigned;
Why `unsigned`?

It should be a signed integer for sure.
Imagine you have 2 iterators `i` and `j = std::next(i)`.
You want to be able to compute:
- `j - i` (1)
- `i - j` (-1)

I'd go for `ptrdiff_t`.

2024-11-20 22:39 UTC, pfez commented on include/revng-c/RestructureCFG/GeneratorIterator.h
> +  // only use we envision is on those objects.
Turn these assumptions into `concept`s, and use them to constrain `T`.

`std::is_trivially_copyable` a `std::is_copy_constructible` and `std::is_copy_assignable` might help.

2024-11-20 22:39 UTC, pfez commented on include/revng-c/RestructureCFG/GeneratorIterator.h
> +  // only use we envision is on those objects.
If you manage to do this, you can move this header out of here, and in `include/ADT`

2024-11-20 22:39 UTC, pfez commented on include/revng-c/RestructureCFG/GeneratorIterator.h
> +  GeneratorIterator(const GeneratorIterator &Other) { *this = Other; }
Why the copy constructor and not the move constructor?

You have the move assignment below, but not the move assignment. Weird...

2024-11-20 22:39 UTC, pfez commented on include/revng-c/RestructureCFG/GeneratorIterator.h
> +  }
The comment is not clear and it doesn't seem to match what happens.
It says that the `GeneratorIterator` is left in `IsDead` state, but
- I think it should say `Other` instead of `GeneratorIterator`
- it doesn't set it to `IsDead` state

2024-11-20 22:39 UTC, pfez commented on include/revng-c/RestructureCFG/GeneratorIterator.h
> +    return *this;
```c++
if (this != &Other) {
  // current body here
}
return *this
```

Otherwise if `this == &Other` you're hopelessly setting it do `IsDead` state.

2024-11-20 22:39 UTC, pfez commented on include/revng-c/RestructureCFG/GeneratorIterator.h
> +  // we are at the end of the `internal_iterator`, we also set the `IsDead`
I don't see the `IsDead` flag being set.

Is the comment old, or you forgot something?

2024-11-20 22:39 UTC, pfez commented on include/revng-c/RestructureCFG/GeneratorIterator.h
> +  mutable bool IsDead = false;
Removing `mutable` from this effectively compiles. I think it's just because you forgot to set `IsDead` in at least one place where `mutable` would have been necessary. But please at the end of the review double check if this is really necessary.

2024-11-20 22:39 UTC, pfez commented on include/revng-c/RestructureCFG/GeneratorIterator.h
> +  mutable cppcoro::generator<T> Coroutine;
Also removing `mutable` from here still compiles.

I'm puzzled, why is `mutable` even needed?

2024-11-20 22:39 UTC, pfez commented on include/revng-c/RestructureCFG/GeneratorIterator.h
> +  GeneratorIterator(const GeneratorIterator &Other) { *this = Other; }
Overall I have some trouble understanding if `GeneratorIterator` is supposed to be:

1. copyable? the fact that it has a `cppcoro::generator` as data member seems to suggest that it souldn't be possible to copy it, because `cppcoro::generator` isn't copyable. but then you go and implement copy constructor and copy assignment. my current understanding is that in principle it shouldn't be copyable, but then there's some code we don't control in LLVM that *needs* to make a copy. Can you explain this in detail?

2. movable? I think that it should be movable. and for extra safety it would be nice that moving it caused the `Coroutine` to be moved too (otherwise you could resume it twice) and set the moved `IsDead` to `true`. Why is the last thing necessary is not clear. Can you explain?

2024-11-20 22:39 UTC, pfez commented on include/revng-c/RestructureCFG/GeneratorIterator.h
> +  GeneratorIterator(const GeneratorIterator &Other) { *this = Other; }
But I like the fact that the implementation of the copy constructor uses the copy assignment. When you implement the move constructor, please make sure that the implementation uses the move assignment.

2024-11-20 22:39 UTC, pfez commented on include/revng-c/RestructureCFG/GeneratorIterator.h
> +    if (Begin != End) {
For extra safety, assert that we're not in `IsDead` state here.

2024-11-20 22:39 UTC, pfez commented on include/revng-c/RestructureCFG/GeneratorIterator.h
> +  }
This comparison operator doesn't handle the `IsDead` case.

Also, I have some doubts about the `IsEnd` state.

Finally, in the final `else` you don't check the `End`s.

So can you explain in more detail how is this supposed to work?

I want to make sure all the corner cases are handled, and that their handling make sense.

2024-11-20 22:39 UTC, pfez commented on include/revng-c/RestructureCFG/GeneratorIterator.h
> +      // handle the `Begin == End` per se
Drop this comment: it nudges you in wanting to drop the next line. Which superfluous now, but it may become necessary depending on how you change `operator==`. So drop the comment and leave the next line.

2024-11-20 22:39 UTC, pfez commented on include/revng-c/RestructureCFG/GotoTargetGraphTraits.h
> +  // TODO: co_return end iterator
This TODO is still not implemented.

2024-11-20 22:39 UTC, pfez commented on include/revng-c/RestructureCFG/ScopeCloserGraphTraits.h
> +  // TODO: co_return end iterator
This TODO is still not implemented.

2024-11-20 22:39 UTC, pfez commented on include/revng-c/RestructureCFG/MarkerCallUtils.h
> +  }
Why are markers still identified by name?

Last time we spoke we said to use `OpaqueFunctionPool`s.

2024-11-20 22:39 UTC, pfez commented on include/revng-c/RestructureCFG/GotoTargetGraphTraits.h
> +struct llvm::GraphTraits<Goto<llvm::BasicBlock *>> {
This is really not what REP 20 says.

You've made 2 different `GraphTrait`s:
1. one for `Goto`, that currently sees `goto` edges *in addition* to regular successors 
2. one for `ScopeCloser`, that currently seed scope closer edges *in addition* to regular successors


REP 20 only talks about a *single* view (the `ScopeGraph) on a CFG that has to do *both* the following
1. *ignore* outgoing edges for blocks that have a `Goto` marker.
2. *see* `ScopeCloser` annotation as edges, even if they don't apper on the CFG.

In addition, a `Goto` marker is only allowed on a block with a single outgoing edge, otherwise the `Goto` marker should also need a second argument to tell which successor is marked as goto and should be ignored by the view.
This condition is not checked in the `verify` and in fact there's even a unit test that breaks it, without failing.

The single view described in REP 20, the `ScopeGraph`, should be the only `GraphTrait` we implement. AFAICT we never need a view that only does something on `Goto` and not on `ScopeCloser` or viceversa.

2024-11-20 22:39 UTC, pfez commented on include/revng-c/RestructureCFG/GotoTargetGraphTraits.h
> +  //       print the `GotoTarget` edges as dashed
This is a cool idea but:
1. first of all you really have to make a single `GraphTrait` representing the `ScopeGraph`
2. then I want the following customizations for:
  - the CFG edges that are "ignored" due to the fact that they are cancelled by a `Goto` marker, should be dashed, and should be marked in graphviz as `[constraint=false]` [as explained here](https://stackoverflow.com/questions/22756929/graphviz-make-edges-not-affecting-the-hierarchy-of-nodes) so that they don't affect the layout of the graph
  - the `ScopeCloser` edges should be marked in a different color

2024-11-20 22:39 UTC, pfez commented on include/revng-c/RestructureCFG/MarkerCallUtils.h
> +  }
I'm not reviewing the rest of the `MarkerCallBuilder` until we clarify this point.

2024-11-27 15:49 UTC, andrealinux1 commented on include/revng-c/RestructureCFG/GeneratorIterator.h
> +  using difference_type = unsigned;
Right, fixed here https://github.com/revng/revng/blob/d8ada1163cf18b087655d87782b79c1a120885c9/include/revng/ADT/GeneratorIterator.h#L27

2024-11-27 15:50 UTC, andrealinux1 commented on include/revng-c/RestructureCFG/GeneratorIterator.h
> +  // only use we envision is on those objects.
Defined a new concept with your suggestions here https://github.com/revng/revng/blob/d8ada1163cf18b087655d87782b79c1a120885c9/include/revng/ADT/GeneratorIterator.h#L16, and moved this header to `include/ADT`

2024-11-27 15:51 UTC, andrealinux1 commented on include/revng-c/RestructureCFG/GeneratorIterator.h
> +  }
The new copy assignment is implemented here https://github.com/revng/revng/blob/d8ada1163cf18b087655d87782b79c1a120885c9/include/revng/ADT/GeneratorIterator.h#L82, but I guess you'll just go through it again in the new review

2024-11-27 15:52 UTC, andrealinux1 commented on include/revng-c/RestructureCFG/GeneratorIterator.h
> +    return *this;
The move assignment has gone, we use the default implementation, added a comment on this here https://github.com/revng/revng/blob/d8ada1163cf18b087655d87782b79c1a120885c9/include/revng/ADT/GeneratorIterator.h#L91

2024-11-27 15:53 UTC, andrealinux1 commented on include/revng-c/RestructureCFG/GeneratorIterator.h
> +  // we are at the end of the `internal_iterator`, we also set the `IsDead`
This method and the pre-dereferentiation mechanism has been removed now

2024-11-27 15:56 UTC, andrealinux1 commented on include/revng-c/RestructureCFG/GeneratorIterator.h
> +  mutable bool IsDead = false;
`mutable` is not necessary with the new implementation, removed it here https://github.com/revng/revng/blob/d8ada1163cf18b087655d87782b79c1a120885c9/include/revng/ADT/GeneratorIterator.h#L38

2024-11-27 15:57 UTC, andrealinux1 commented on include/revng-c/RestructureCFG/GeneratorIterator.h
> +  mutable cppcoro::generator<T> Coroutine;
In the new implementation `mutable` is not necessary here https://github.com/revng/revng/blob/d8ada1163cf18b087655d87782b79c1a120885c9/include/revng/ADT/GeneratorIterator.h#L39

2024-11-27 15:57 UTC, andrealinux1 commented on include/revng-c/RestructureCFG/GeneratorIterator.h
> +    if (Begin != End) {
This method doesn't exists anymore, but now every method checks the `IsDead` state as first thing

2024-11-27 15:59 UTC, andrealinux1 commented on include/revng-c/RestructureCFG/GeneratorIterator.h
> +  }
The `IsDead` is now checked at the beginning of this method https://github.com/revng/revng/blob/d8ada1163cf18b087655d87782b79c1a120885c9/include/revng/ADT/GeneratorIterator.h#L97, and I added a comment here https://github.com/revng/revng/blob/d8ada1163cf18b087655d87782b79c1a120885c9/include/revng/ADT/GeneratorIterator.h#L104 explaining why we special case the situation where either `this` or `Other` is a sentinel end iterator

2024-11-27 15:59 UTC, andrealinux1 commented on include/revng-c/RestructureCFG/GeneratorIterator.h
> +      // handle the `Begin == End` per se
This has been dropped

2024-11-27 16:01 UTC, andrealinux1 commented on include/revng-c/RestructureCFG/ScopeCloserGraphTraits.h
> +  // TODO: co_return end iterator
I now `co_return` here https://github.com/revng/revng/blob/d8ada1163cf18b087655d87782b79c1a120885c9/include/revng/RestructureCFG/ScopeGraphGraphTraits.h#L35

2024-11-27 16:01 UTC, andrealinux1 commented on include/revng-c/RestructureCFG/GotoTargetGraphTraits.h
> +  // TODO: co_return end iterator
This `GraphTrait` disappeared

2024-11-27 16:03 UTC, andrealinux1 commented on include/revng-c/RestructureCFG/MarkerCallUtils.h
> +  }
We agreed on using the `FunctionTag` mechanism, this is now implemented and specifically we use this routine https://github.com/revng/revng/blob/d8ada1163cf18b087655d87782b79c1a120885c9/include/revng/RestructureCFG/MarkerCallUtils.h#L21 to perform the `MarkerCallFunction` retrieval

2024-11-27 16:13 UTC, andrealinux1 commented on include/revng-c/RestructureCFG/GotoTargetGraphTraits.h
> +  //       print the `GotoTarget` edges as dashed
Agree with your observations on how we would implement the graph, but this cannot be done at the moment due to how the `DotGraphWriter` wants to copy the edge iterators, something that we cannot do at the moment. Indeed this TODO was more a "we may want to do this in the future", in order to not loose track of the idea. I added to the comment your precisation on how we would mark the edges with different colors and the `constraint` thing here https://github.com/revng/revng/blob/8fbde7a81df05ca5e3c9ec29a0d416dc599e414f/include/revng/RestructureCFG/ScopeGraphGraphTraits.h#L115, but I would say we may want to not tackle this now.

2024-11-27 16:16 UTC, andrealinux1 commented on include/revng-c/RestructureCFG/GeneratorIterator.h
> +  GeneratorIterator(const GeneratorIterator &Other) { *this = Other; }
I think we discussed this a lot in person last time, so I guess most of the doubts here have been already resolved, and it may be more useful to comment the new version on the new PR, but let me know if you want some extra clarifications on this point

2024-11-27 16:17 UTC, andrealinux1 commented on include/revng-c/RestructureCFG/GotoTargetGraphTraits.h
> +struct llvm::GraphTraits<Goto<llvm::BasicBlock *>> {
You are right, as we discussed in person on this last time. The new implementation should reflect what we discussed, so I think you'll directly comment on that on the new PR.

2024-12-05 15:22 UTC, pfez commented
I'm closing this since this PR has already been migrated to revng

2024-12-05 15:22 UTC, closed without merging